language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install https://www.djangoproject.com/download/1.7a2/tarball/
  - pip install -q -r requirements.txt --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 finalware"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W finalware; fi
script: python manage.py test


